sudo: required
services:
  - docker

before_install:
  - docker build -t fionactc/docker-react -f Dockerfile.dev .

# travis assumes test that does not exit after running is problematic
# Therefore -- --coverage is added to exit test
script:
  - docker run fionactc/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-814228185306"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
